version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_test_db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'mydb'
    ports:
      - '3307:3306'
    volumes:
      - ./backend/neogul-map/neogul-map/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
