spring:
  application:
    name: neogul-map
  datasource:
    url: jdbc:h2:mem:neogul-map-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 이미지 업로드 설정
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
    enabled: true

# 이미지 업로드 경로 설정
app:
  image:
    upload-path: uploads/profiles/
    max-size: 10485760  # 10MB in bytes

# 파일 업로드 디렉토리 설정
file:
  upload-dir: uploads/profiles/

# JWT 설정
jwt:
  secret: bmVvZ3VsbWFwLWp3dC1zZWNyZXQta2V5LWZvci1kZXZlbG9wbWVudC1hbmQtdGVzdGluZy1wdXJwb3Nlcw==  # Base64 encoded secret
  token-validity-in-seconds: 7200  # 2시간